name: YouTube Audio → Drive (Manual Run)

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: yt-audio-drive
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Tăng thời gian chờ cho các danh sách dài
    env:
      # --- ĐÍCH ---
      GDRIVE_FOLDER_ID: "1V9qkTesXnogNiTPUvDZOwJPj4Op4lTHF"
      GDRIVE_OAUTH_TOKEN_JSON: ${{ secrets.GDRIVE_OAUTH_TOKEN_JSON }}
      GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}

      # --- DL ---
      PO_TOKEN: ${{ secrets.PO_TOKEN }}
      SLEEP_SECONDS: "5"
      MAX_PER_RUN: "99999"  # <<< Xử lý tất cả link trong một lần chạy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (cache pip)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Install system ffmpeg (with ffprobe)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Ensure data folder & files
        run: |
          mkdir -p data/audio
          [ -f data/links.txt ] || : > data/links.txt
          [ -f data/dalay.txt ] || : > data/dalay.txt

      - name: Debug links.txt (head)
        run: |
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "links.txt size: $(wc -c < data/links.txt) bytes | lines: $(wc -l < data/links.txt)"
          sed -n '1,10p' data/links.txt | nl -ba || true
          echo "done lines: $(wc -l < data/dalay.txt || echo 0)"

      - name: Run downloader (all links, upload to Drive)
        env:
          PYTHONUNBUFFERED: "1"
          PYTHONUTF8: "1"
        run: |
          python -u scripts/yt_audio_to_drive.py

      - name: Commit updated dalay.txt (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code -- data/dalay.txt; then
            echo "No changes in dalay.txt"
          else
            git add data/dalay.txt
            git commit -m "chore: update dalay.txt (YouTube audio processed)"
            git push
          fi
