name: YouTube Audio → Drive (no artifact)

on:
  workflow_dispatch: {}
  schedule:
    # Asia/Bangkok (UTC+7): 10:00, 16:00, 22:00
    - cron: "0 3 * * *"
    - cron: "0 9 * * *"
    - cron: "0 15 * * *"

permissions:
  contents: write

concurrency:
  group: yt-audio-drive
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # --- BẮT BUỘC ---
      # Folder bạn cung cấp:
      GDRIVE_FOLDER_ID: "1V9qkTesXnogNiTPUvDZOwJPj4Op4lTHF"
      # DÁN NGUYÊN VĂN JSON của SA (email: gdrive-automation@hidden-matter-469404-t5.iam.gserviceaccount.com)
      GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}

      # --- TUỲ CHỌN ---
      PO_TOKEN: ${{ secrets.PO_TOKEN }}
      SLEEP_SECONDS: "8"
      # Bật test đẩy file nhỏ khi links.txt rỗng:
      # SMOKE_TEST: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (cache pip)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Ensure data folder & files
        run: |
          mkdir -p data/audio
          [ -f data/links.txt ] || : > data/links.txt
          [ -f data/dalay.txt ] || : > data/dalay.txt

      - name: Run downloader (upload thẳng Drive)
        run: |
          python scripts/yt_audio_to_drive.py

      - name: Commit updated dalay.txt (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code -- data/dalay.txt; then
            echo "No changes in dalay.txt"
          else
            git add data/dalay.txt
            git commit -m "chore: update dalay.txt (YouTube audio processed)"
            git push
          fi
