name: YouTube Audio → Drive (no artifact, 1 link/run)

on:
  workflow_dispatch: {}
  schedule:
    # Asia/Bangkok (UTC+7): 10:00, 16:00, 22:00
    - cron: "0 3 * * *"
    - cron: "0 9 * * *"
    - cron: "0 15 * * *"

permissions:
  contents: write

concurrency:
  group: yt-audio-drive
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # --- THƯ MỤC ĐÍCH ---
      GDRIVE_FOLDER_ID: "1V9qkTesXnogNiTPUvDZOwJPj4Op4lTHF"

      # --- ƯU TIÊN OAUTH (khuyên dùng để tránh quota SA) ---
      # Đặt secret chứa TOÀN BỘ JSON token OAuth (đã cấp Drive):
      # GDRIVE_OAUTH_TOKEN_JSON: ${{ secrets.GDRIVE_OAUTH_TOKEN_JSON }}
      GDRIVE_OAUTH_TOKEN_JSON: ${{ secrets.GDRIVE_OAUTH_TOKEN_JSON }}

      # --- FALLBACK: SERVICE ACCOUNT (nếu không có OAuth) ---
      # Dán nguyên văn JSON Service Account
      GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}

      # --- TUỲ CHỌN ---
      PO_TOKEN: ${{ secrets.PO_TOKEN }}
      SLEEP_SECONDS: "2"     # bạn muốn 2s giữa các link (ở đây chỉ 1 link/run)
      # SMOKE_TEST: "1"      # bật nếu muốn thử upload file test khi links.txt rỗng

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (cache pip)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Ensure data folder & files
        run: |
          mkdir -p data/audio
          [ -f data/links.txt ] || : > data/links.txt
          [ -f data/dalay.txt ] || : > data/dalay.txt

      - name: Run downloader (1 link only, upload thẳng Drive)
        run: |
          python scripts/yt_audio_to_drive.py

      - name: Commit updated dalay.txt (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code -- data/dalay.txt; then
            echo "No changes in dalay.txt"
          else
            git add data/dalay.txt
            git commit -m "chore: update dalay.txt (YouTube audio processed)"
            git push
          fi
