name: YouTube Audio → Drive (chạy đến khi hết links.txt)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write

concurrency:
  group: yt-audio-drive
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    # Tăng thời gian nếu danh sách rất dài; GitHub-hosted runner thường giới hạn tối đa ~6h/job.
    timeout-minutes: 360
    env:
      # --- ĐÍCH ---
      GDRIVE_FOLDER_ID: "1V9qkTesXnogNiTPUvDZOwJPj4Op4lTHF"
      # Ưu tiên OAuth (tránh quota SA ở My Drive)
      GDRIVE_OAUTH_TOKEN_JSON: ${{ secrets.GDRIVE_OAUTH_TOKEN_JSON }}
      # Fallback SA (nếu không có OAuth)
      GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}

      # --- DL ---
      PO_TOKEN: ${{ secrets.PO_TOKEN }}
      SLEEP_SECONDS: "5"
      MAX_PER_RUN: "100"  # script của bạn sẽ xử lý tối đa N link mỗi lượt gọi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (cache pip)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Install system ffmpeg (with ffprobe)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Ensure data folder & files
        run: |
          mkdir -p data/audio
          [ -f data/links.txt ] || : > data/links.txt
          [ -f data/dalay.txt ] || : > data/dalay.txt

      - name: Debug links.txt (head)
        run: |
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "links.txt size: $(wc -c < data/links.txt) bytes | lines: $(wc -l < data/links.txt)"
          sed -n '1,10p' data/links.txt | nl -ba || true
          echo "done lines: $(wc -l < data/dalay.txt || echo 0)"

      - name: Run downloader liên tục đến khi hết link
        env:
          PYTHONUNBUFFERED: "1"
          PYTHONUTF8: "1"
        run: |
          set -e
          count_remain () {
            bash -lc '
              grep -Ev "^\s*(#|$)" data/links.txt | sort > /tmp/all || true
              grep -Ev "^\s*(#|$)" data/dalay.txt | sort > /tmp/done || true
              comm -23 /tmp/all /tmp/done | wc -l
            '
          }
          nochange=0
          prev=$(count_remain)
          echo "Remaining (start): $prev"
          while [ "$prev" -gt 0 ]; do
            echo "::group::Run downloader (batch up to ${MAX_PER_RUN:-100})"
            python -u scripts/yt_audio_to_drive.py || true
            echo "::endgroup::"
            sleep "${SLEEP_SECONDS:-5}"
            cur=$(count_remain)
            echo "Remaining (after batch): $cur"
            if [ "$cur" -ge "$prev" ]; then
              nochange=$((nochange+1))
            else
              nochange=0
            fi
            # tránh vòng lặp vô hạn khi link lỗi liên tục:
            if [ "$nochange" -ge 3 ]; then
              echo "Không tiến triển sau 3 vòng lặp. Dừng để tránh loop vô hạn."
              break
            fi
            prev="$cur"
          done
          echo "Hoàn tất: không còn link mới cần xử lý hoặc không tiến triển."

      - name: Commit updated dalay.txt (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code -- data/dalay.txt; then
            echo "No changes in dalay.txt"
          else
            git add data/dalay.txt
            git commit -m "chore: update dalay.txt (YouTube audio processed)"
            git push
          fi
